package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/daniil-lyalko/pacer/internal/context"
	"github.com/daniil-lyalko/pacer/internal/git"
	"github.com/spf13/cobra"
)

var autoDROPBAGCmd = &cobra.Command{
	Use:    "auto-dropbag",
	Short:  "Auto-generate DROPBAG (called by Stop hook)",
	Hidden: true,
	Long: `Auto-generates a DROPBAG file from current git state.

Called by the Stop hook (async) after every Claude response.
Debounced: skips if last write was <60s ago AND no git changes detected.

Reads transcript_path from stdin JSON (provided by Claude Code Stop hook),
but for v1 implementation, just captures git status + recent commits.`,
	RunE: runAutoDROPBAG,
}

func init() {
	rootCmd.AddCommand(autoDROPBAGCmd)
}

func runAutoDROPBAG(cmd *cobra.Command, args []string) error {
	// Get current directory
	cwd, err := os.Getwd()
	if err != nil {
		return err
	}

	// Get repo root
	if !git.IsGitRepo(cwd) {
		return nil // Not in a git repo, skip silently
	}

	dir, err := git.GetRepoRoot(cwd)
	if err != nil {
		return nil
	}

	dropbagsDir := filepath.Join(dir, ".pacer", "dropbags")
	if err := os.MkdirAll(dropbagsDir, 0755); err != nil {
		return nil // Silent failure
	}

	// Debounce: check if last auto-DROPBAG was recent
	latestAuto := findLatestAutoDROPBAG(dropbagsDir)
	if latestAuto != "" {
		info, err := os.Stat(latestAuto)
		if err == nil && time.Since(info.ModTime()) < 60*time.Second {
			// Check if git has changes since last write
			hasChanges, _ := git.HasUncommittedChanges(dir)
			if !hasChanges {
				return nil // Skip - too recent and no changes
			}
		}
	}

	// Generate DROPBAG content
	ctx, err := context.GatherContext(dir)
	if err != nil {
		return nil // Silent failure
	}

	content := formatAutoDROPBAG(ctx)

	// Write to timestamped file
	timestamp := time.Now().Format("2006-01-02-1504")
	filename := fmt.Sprintf("DROPBAG-auto-%s.md", timestamp)
	path := filepath.Join(dropbagsDir, filename)

	return os.WriteFile(path, []byte(content), 0644)
}

// findLatestAutoDROPBAG returns the path to the most recent DROPBAG-auto-*.md file
func findLatestAutoDROPBAG(dropbagsDir string) string {
	entries, err := os.ReadDir(dropbagsDir)
	if err != nil {
		return ""
	}

	var latest string
	var latestTime time.Time

	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		name := entry.Name()
		if !strings.HasPrefix(name, "DROPBAG-auto-") || !strings.HasSuffix(name, ".md") {
			continue
		}

		path := filepath.Join(dropbagsDir, name)
		info, err := os.Stat(path)
		if err != nil {
			continue
		}

		if latest == "" || info.ModTime().After(latestTime) {
			latest = path
			latestTime = info.ModTime()
		}
	}

	return latest
}

// formatAutoDROPBAG generates DROPBAG markdown from context
func formatAutoDROPBAG(ctx *context.ContextOutput) string {
	var buf strings.Builder

	buf.WriteString("# Auto-DROPBAG\n\n")
	buf.WriteString("*Auto-generated by `pacer auto-dropbag`*\n\n")
	buf.WriteString("---\n\n")

	// Branch
	if ctx.BranchName != "" {
		buf.WriteString(fmt.Sprintf("**Branch:** %s\n\n", ctx.BranchName))
	}

	// Modified files
	if ctx.GitStatus != nil {
		if len(ctx.GitStatus.ModifiedFiles) > 0 || len(ctx.GitStatus.StagedFiles) > 0 {
			buf.WriteString("## Modified Files\n\n")
			if len(ctx.GitStatus.StagedFiles) > 0 {
				buf.WriteString("**Staged:**\n")
				for _, f := range ctx.GitStatus.StagedFiles {
					buf.WriteString(fmt.Sprintf("- %s\n", f))
				}
				buf.WriteString("\n")
			}
			if len(ctx.GitStatus.ModifiedFiles) > 0 {
				buf.WriteString("**Unstaged:**\n")
				for _, f := range ctx.GitStatus.ModifiedFiles {
					buf.WriteString(fmt.Sprintf("- %s\n", f))
				}
				buf.WriteString("\n")
			}
		}
	}

	// Recent commits
	if len(ctx.Commits) > 0 {
		buf.WriteString("## Recent Commits\n\n")
		for _, commit := range ctx.Commits {
			buf.WriteString(fmt.Sprintf("- %s\n", commit))
		}
		buf.WriteString("\n")
	}

	return buf.String()
}
